### PR TITLE
Use magento deployment version

### PR DESCRIPTION
**Pull request by DominicWatts**
Use magento static signing deployment version instead of text file

### CODE REVIEW

**Comment by DominicWatts** [comment]
I thought this was quite a good idea. Any feedback?

**Comment by royduin** [comment]
@JosephMaxwell maybe? He created the release txt here: https://github.com/justbetter/magento2-sentry/pull/26. Else @tdgroot or @peterjaap maybe? They supported the idea. And of course @rakibabu who's maintaining the module. Any thoughts?

**Comment by peterjaap** [comment]
Well I'm not the maintainer but LGTM!

**Comment by JosephMaxwell** [comment]
@royduin for our internal purposes the deployment version is great, too.

**Comment by rakibabu** [comment]
@DominicWatts , I think the deployment version is a great way. I'll merge it, thanks for contributing.

**Pull request merged**
