### PR TITLE
Initial v2 commit

### PR DESCRIPTION
**Pull request by JosephMaxwell**
**Summary**

This upgrades Sentry to use v2 of the Sentry SDK. I've been testing this on a almost-production website and am very happy with the results.

I have releases configured in our build pipeline, and the `var/sentry-releaseid.txt` is the last step in that process.

The biggest help of going to v2 is that Sentry has global exception handlers. That makes it much easier for errors to be caught.

**Result**

I built unit tests for `GlobalExceptionCatcher`. As I have time, I'd like to add more tests.

### CODE REVIEW

**Comment by rakibabu** [comment]
Hi @JosephMaxwell ,

Thanks for making this PR and contributing!

I believe we doesn't have to work with .txt files to make send the version to sentry. We should rework this with git tags or something like that.

The functionality with the exception catcher looks nice. Lets rework the version and some PSR-2 fixes so we can release this shortly.

Thanks again.

**Comment by tdgroot** [comment]
@rakibabu I actually like the release version text file. On production environments, I do not have any information about git tag/commit hash.

**Comment by rakibabu** [comment]
Hi @tdgroot ,

Thanks for the feedback.
Let's debate any solution to implement this version tag dynamically with a text file or any other solution. 

Maybe we can configure some options to choose between text and git version tags in the module?

**Comment by JosephMaxwell** [comment]
@tdgroot thanks. I agree with you.

@rakibabu Frankly, my opinion with M2 is that you _should be_ utilizing a build pipeline of sorts, otherwise the merchant faces downtime. In such a build pipeline, it's easy to hook up Sentry releases and drop whatever you want into the release txt file.

**Comment by royduin** [comment]
Make release information optional? So the user can implement it however they like as also done with the Laravel Sentry integration: https://github.com/getsentry/sentry-laravel/blob/master/config/sentry.php#L8. Now you're forcing a user to use an txt, maybe they already have a version number elsewhere.

**Comment by JosephMaxwell** [comment]
@royduin the txt file right now is optional. It wouldn't be hard to add the git tag, too.

**Comment by royduin** [comment]
Yes I see but maybe someone has defined a constant with a version number? Or likes to use a Git tag/hash, etc... I think making it optional configurable is the way to go. An option in the `env.php` maybe just like the integration for Laravel?

**Comment by DominicWatts** [comment]
Sorry to jump in and maybe I misunderstand but M2 already has a built in 'release ID' generation system. If you have static content signing enabled you can get an ID from pub/static/deployed_version.txt

https://devdocs.magento.com/guides/v2.3/config-guide/cache/static-content-signing.html#static-content-signing

Static content deploy for us is a core part of any M2 deployment procedure

**Comment by peterjaap** [comment]
I'd +1 using the `deployed_version.txt` as a first measure, and maybe implement a mechanism that allows for adding fallback options to assess the deployed version.

**Comment by tdgroot** [comment]
+1 for `deployed_version.txt`!

**Comment by JosephMaxwell** [comment]
@rakibabu looks like we are getting some consensus here.

**Comment by rakibabu** [comment]
@JosephMaxwell ,

Can you make this PR to develop? I'll refactor it myself and release it in the near feature. Anywhere in this month.

Kind regards,

Rakhal Imming

**Comment by JosephMaxwell** [comment]
@rakibabu ,

I'm not following you here. Do you need me to merge in #29 into this?

Joseph

**Comment by rakibabu** [comment]
Hi @JosephMaxwell ,

The question here is to have your pull request send to develop. In this way I can refactor all requests in one new release.

Rakhal

**Comment by royduin** [comment]
Here you go @rakibabu 👍

**Comment by Niko9911** [comment]
I will be doing some fixes to his PR related this file permissions, stay tuned.

**Comment by Niko9911** [comment]
please see https://github.com/JosephMaxwell/magento2-sentry/pull/1/files

**Comment by Niko9911** [comment]
Ping @royduin @rakibabu @JosephMaxwell 

Can we progress with this?
@JosephMaxwell Can you merge my PRs into your fork?
@rakibabu I can make my own PR from this fork if you want with the fixes. I would like avoid me forking this project due of this feature missing.

**Comment by DominicWatts** [comment]
Also `/Plugin/MonologPlugin.php` as per original functionality still has proxies explicitly requested in constructor.  Is this still the right thing to do?

**Comment by Niko9911** [comment]
Thank you.

**Comment by JosephMaxwell** [comment]
@rakibabu thanks for working on this. I apologize for not getting back sooner here. It looks like everything is getting sorted out?

**Comment by DominicWatts** [comment]
I created pull request to use magento internal release ID

https://github.com/justbetter/magento2-sentry/pull/37

**Pull request merged**
